import { INITIAL_PROVINCES, INITIAL_DISTRICTS } from './data/mozambiqueLocations';

export const initialData = {
  users: [
    { id: 'ST849547771', name: 'Administrador Geral', email: 'slaitertripas@gmail.com', role: 'admin' as const, roleTitle: 'Administrador Geral do Sistema', department: 'Tecnologias da Informação', password: '231383', mustChangePassword: false },
    { id: 'u1-gov', name: 'Administrador Geral (Gov)', email: 'admin@gov.mz', role: 'admin' as const, roleTitle: 'Administrador de Sistemas do Governo', department: 'Governo de Moçambique', password: 'admin' },
    { id: 'u6', name: 'Gestor do Ministério (MINEDH)', email: 'ministro@gov.mz', role: 'national' as const, roleTitle: 'Ministério da Educação (MINEDH)', department: 'Gabinete Ministerial', password: 'ministro' },
    { id: 'u7', name: 'Gestor Provincial (DPE Maputo)', email: 'provincial@gov.mz', role: 'provincial' as const, roleTitle: 'Director Provincial (DPE)', department: 'Direção Provincial de Educação', provinceId: 'p1', password: 'provincial' },
    { id: 'u8', name: 'Gestor Distrital (SDEJT KaMpfumo)', email: 'distrital@gov.mz', role: 'district' as const, roleTitle: 'Director Distrital (SDEJT)', department: 'Serviço Distrital de Educação', districtId: 'd1', provinceId: 'p1', password: 'distrital' },
    { id: 'u2', name: 'Dr. Manuel Mabote', email: 'diretor@escola.com', role: 'director' as const, roleTitle: 'Director da Escola Josina Machel', department: 'Direcção da Escola', schoolId: 's1', password: 'diretor' },
    { id: 'u3', name: 'Dr. João Pedagógico', email: 'pedagogico@escola.com', role: 'pedagogical' as const, roleTitle: 'Director Adjunto Pedagógico (Todos os Ciclos)', department: 'Pedagógico Geral', pedagogicalCycle: 'todos', schoolId: 's1', password: 'pedagogico' },
    { id: 'u-dap1', name: 'Dra. Lurdes Pedagógica (1º Ciclo)', email: 'dap1@escola.com', role: 'pedagogical_c1' as const, roleTitle: 'Director Adjunto Pedagógico (1º Ciclo)', department: 'Pedagógico 1º Ciclo', pedagogicalCycle: 'ciclo1', schoolId: 's1', password: 'dap1' },
    { id: 'u-dap2', name: 'Prof. Zito Pedagógico (ESG1)', email: 'dap2@escola.com', role: 'pedagogical_c2' as const, roleTitle: 'Director Adjunto Pedagógico (2º Ciclo ESG1)', department: 'Pedagógico ESG1', pedagogicalCycle: 'ciclo2_esg1', schoolId: 's1', password: 'dap2' },
    { id: 'u-dap3', name: 'Dra. Graça Pedagógica (ESG2)', email: 'dap3@escola.com', role: 'pedagogical_c3' as const, roleTitle: 'Director Adjunto Pedagógico (2º Ciclo ESG2)', department: 'Pedagógico ESG2', pedagogicalCycle: 'ciclo2_esg2', schoolId: 's1', password: 'dap3' },
    { id: 'u4', name: 'Prof. Alberto Nhatitima', email: 'professor@escola.com', role: 'teacher' as const, roleTitle: 'Professor de Matemática', department: 'Corpo Docente', schoolId: 's1', password: 'professor' },
    { id: 'u5', name: 'Dra. Ana Secretaria', email: 'secretaria@escola.com', role: 'secretariat' as const, roleTitle: 'Chefe da Secretaria Escolar', department: 'Secretaria Geral', schoolId: 's1', password: 'secretaria' },
    { id: 'u-rh', name: 'Dra. Maria Recursos Humanos', email: 'rh@escola.com', role: 'secretariat_rh' as const, roleTitle: 'Técnica de Recursos Humanos', department: 'Secretaria • RH', schoolId: 's1', password: 'rh' },
    { id: 'u-pat', name: 'Sr. Fernando Património', email: 'patrimonio@escola.com', role: 'secretariat_patrimonio' as const, roleTitle: 'Gestor de Património', department: 'Secretaria • Património', schoolId: 's1', password: 'patrimonio' },
    { id: 'u-fin', name: 'Dr. Tomás Tesoureiro', email: 'financas@escola.com', role: 'financial' as const, roleTitle: 'Gestor Financeiro da Escola', department: 'Finanças & Tesouraria', schoolId: 's1', password: 'financas' },
    { id: 'u-rec', name: 'Dra. Sofia Recepção', email: 'recepcao@escola.com', role: 'secretariat_recepcao' as const, roleTitle: 'Atendimento e Recepção', department: 'Secretaria • Atendimento', schoolId: 's1', password: 'recepcao' },
    { id: 'u-arq', name: 'Sr. Paulo Arquivista', email: 'arquivo@escola.com', role: 'secretariat_arquivo' as const, roleTitle: 'Arquivista Escolar', department: 'Secretaria • Arquivo', schoolId: 's1', password: 'arquivo' },
    { id: 'u-bib', name: 'Dra. Beatriz Bibliotecária', email: 'biblioteca@escola.com', role: 'librarian' as const, roleTitle: 'Bibliotecária Principal', department: 'Biblioteca Escolar', schoolId: 's1', password: 'biblioteca' },
    { id: 'u-st01', name: 'Artur Aluno', email: 'aluno@escola.com', role: 'student' as const, roleTitle: 'Estudante da 10ª Classe', studentId: 'st01', schoolId: 's1', password: 'aluno' },
    { id: 'u-annie', name: 'Annie Tripalonga Vicente', email: 'annie@escola.com', role: 'student' as const, roleTitle: 'Estudante da 7ª Classe', studentId: 'st-annie', schoolId: 's1', password: 'annie' },
    { id: 'u-enc', name: 'Sr. Carlos Aluno (Encarregado)', email: 'encarregado@escola.com', role: 'guardian' as const, roleTitle: 'Encarregado de Educação', guardianStudentIds: ['st01', 'st-annie'], schoolId: 's1', password: 'encarregado' },
  ],
  provinces: INITIAL_PROVINCES,
  districts: INITIAL_DISTRICTS,
  schools: [
    { 
      id: 's1', 
      name: 'Escola Secundária Josina Machel', 
      code: 'ESC-MAP-001',
      managementType: 'estatal',
      province: 'Maputo Cidade', 
      district: 'KaMpfumo', 
      address: 'Av. Mao Tse Tung, nº 1420', 
      districtId: 'd1',
      schoolTypes: ['ENSINO SECUNDÁRIO DO 1 CICLO', 'ENSINO SECUNDÁRIO DO 2 CICLO'],
    }
  ],
  classes: [
    { id: 'c-7a', schoolId: 's1', name: '7ª Turma A', gradeLevel: '7ª Classe', year: 2026, period: 'Manhã', shift: 'Diurno', area: 'CS' },
    { id: 'c1', schoolId: 's1', name: '10ª Turma A', gradeLevel: '10ª Classe', year: 2026, period: 'Manhã', shift: 'Diurno', area: 'CS' },
    { id: 'c2', schoolId: 's1', name: '10ª Turma B', gradeLevel: '10ª Classe', year: 2026, period: 'Tarde', shift: 'Diurno', area: 'MCN' },
    { id: 'c3', schoolId: 's1', name: '11ª Turma A', gradeLevel: '11ª Classe', year: 2026, period: 'Manhã', shift: 'Diurno', area: 'CS' },
    { id: 'c4', schoolId: 's1', name: '12ª Turma A', gradeLevel: '12ª Classe', year: 2026, period: 'Manhã', shift: 'Diurno', area: 'MCN' },
    { id: 'c5', schoolId: 's1', name: '8ª Turma A', gradeLevel: '8ª Classe', year: 2026, period: 'Manhã', shift: 'Diurno', area: 'CS' },
    { id: 'c6', schoolId: 's1', name: '9ª Turma B', gradeLevel: '9ª Classe', year: 2026, period: 'Tarde', shift: 'Diurno', area: 'CS' },
  ],
  students: [
    {
      id: 'st-annie',
      name: 'Annie Vicente',
      fullName: 'Annie Tripalonga Vicente',
      studentCode: 'EST-2026-ANNIE',
      loginId: 'ALU-7CLASSE',
      schoolId: 's1',
      classId: 'c-7a',
      gender: 'F',
      birthDate: '2013-08-20',
      enrollmentDate: '2026-01-15',
      gradeLevel: '7ª Classe',
      status: 'active' as const,
      frequencyNumber: 1,
      studentNumber: '7001',
      processCode: 'PROC-2026-701'
    },
    {
      id: 'st01',
      name: 'Artur Aluno',
      fullName: 'Artur Alberto Aluno',
      studentCode: 'EST-2026-001',
      loginId: 'ALU-2026-001',
      schoolId: 's1',
      classId: 'c1',
      gender: 'M',
      birthDate: '2008-04-12',
      enrollmentDate: '2026-01-15',
      gradeLevel: '10ª Classe',
      status: 'active' as const,
      frequencyNumber: 1,
      studentNumber: '1001',
      processCode: 'PROC-2026-001'
    },
    {
      id: 'st02',
      name: 'Beatriz Machel',
      fullName: 'Beatriz Samora Machel',
      studentCode: 'EST-2026-002',
      loginId: 'ALU-2026-002',
      schoolId: 's1',
      classId: 'c1',
      gender: 'F',
      birthDate: '2008-09-21',
      enrollmentDate: '2026-01-15',
      gradeLevel: '10ª Classe',
      status: 'active' as const,
      frequencyNumber: 2,
      studentNumber: '1002',
      processCode: 'PROC-2026-002'
    },
    {
      id: 'st03',
      name: 'Carlos Tembe',
      fullName: 'Carlos Mateus Tembe',
      studentCode: 'EST-2026-003',
      loginId: 'ALU-2026-003',
      schoolId: 's1',
      classId: 'c1',
      gender: 'M',
      birthDate: '2008-11-05',
      enrollmentDate: '2026-01-16',
      gradeLevel: '10ª Classe',
      status: 'active' as const,
      frequencyNumber: 3,
      studentNumber: '1003',
      processCode: 'PROC-2026-003'
    },
    {
      id: 'st04',
      name: 'Denise Macamo',
      fullName: 'Denise Maria Macamo',
      studentCode: 'EST-2026-004',
      loginId: 'ALU-2026-004',
      schoolId: 's1',
      classId: 'c2',
      gender: 'F',
      birthDate: '2008-02-18',
      enrollmentDate: '2026-01-16',
      gradeLevel: '10ª Classe',
      status: 'active' as const,
      frequencyNumber: 1,
      studentNumber: '1004',
      processCode: 'PROC-2026-004'
    },
    {
      id: 'st05',
      name: 'Eduardo Mondlane Jr',
      fullName: 'Eduardo Chivambo Mondlane Jr',
      studentCode: 'EST-2026-005',
      loginId: 'ALU-2026-005',
      schoolId: 's1',
      classId: 'c4',
      gender: 'M',
      birthDate: '2006-06-20',
      enrollmentDate: '2026-01-10',
      gradeLevel: '12ª Classe',
      status: 'active' as const,
      frequencyNumber: 1,
      studentNumber: '1005',
      processCode: 'PROC-2026-005'
    }
  ],
  subjects: [
    { id: 'sub1', name: 'Português', area: 'CS' },
    { id: 'sub2', name: 'Matemática', area: 'MCN' },
    { id: 'sub3', name: 'Inglês', area: 'CS' },
    { id: 'sub4', name: 'Física', area: 'MCN' },
    { id: 'sub5', name: 'Química', area: 'MCN' },
    { id: 'sub6', name: 'Biologia', area: 'MCN' },
    { id: 'sub7', name: 'História', area: 'CS' },
    { id: 'sub8', name: 'Geografia', area: 'CS' },
  ],
  assignments: [
    { id: 'as-annie-cls', teacherId: 'u4', classId: 'c-7a', subjectId: 'sub1', className: '7ª Turma A', subjectName: 'Português', teacherName: 'Prof. Alberto Nhatitima', schoolId: 's1' },
    { id: 'as1', teacherId: 'u4', classId: 'c1', subjectId: 'sub2', className: '10ª Turma A', subjectName: 'Matemática', teacherName: 'Prof. Alberto Nhatitima', schoolId: 's1' },
    { id: 'as2', teacherId: 'u4', classId: 'c2', subjectId: 'sub2', className: '10ª Turma B', subjectName: 'Matemática', teacherName: 'Prof. Alberto Nhatitima', schoolId: 's1' },
    { id: 'as3', teacherId: 'u4', classId: 'c4', subjectId: 'sub2', className: '12ª Turma A', subjectName: 'Matemática', teacherName: 'Prof. Alberto Nhatitima', schoolId: 's1' },
  ],
  grades: [
    { id: 'g1', studentId: 'st01', classId: 'c1', subjectId: 'sub2', teacherId: 'u4', schoolId: 's1', acs1: 14, acs2: 15, apt: 16, media: 15, trimester: 1, year: 2026 },
    { id: 'g2', studentId: 'st01', classId: 'c1', subjectId: 'sub1', teacherId: 'u4', schoolId: 's1', acs1: 13, acs2: 14, apt: 14, media: 14, trimester: 1, year: 2026 },
    { id: 'g3', studentId: 'st02', classId: 'c1', subjectId: 'sub2', teacherId: 'u4', schoolId: 's1', acs1: 16, acs2: 17, apt: 18, media: 17, trimester: 1, year: 2026 },
    { id: 'g4', studentId: 'st03', classId: 'c1', subjectId: 'sub2', teacherId: 'u4', schoolId: 's1', acs1: 12, acs2: 13, apt: 11, media: 12, trimester: 1, year: 2026 },
  ],
  examGrades: [],
  reports: [],
  employees: [
    { id: 'emp1', schoolId: 's1', name: 'Dr. Manuel Mabote', role: 'Director Geral', roleFunction: 'Director', career: 'Docente', gender: 'M', email: 'diretor@escola.com', phone: '+258 84 100 0001', nuit: '102938475', contractLink: 'Nomeação Definitiva', isEffective: 'Sim', maritalStatus: 'Casado', fatherName: 'Mabote Pai', motherName: 'Mabote Mãe', idCardNumber: '1102938475A', idCardIssuedAt: 'Maputo', idCardIssuedDate: '2015-05-10', nationality: 'Moçambicana', birthProvince: 'Maputo', birthDistrict: 'KaMpfumo', birthDate: '1975-03-12' },
    { id: 'emp2', schoolId: 's1', name: 'Dr. João Pedagógico', role: 'Director Adjunto Pedagógico', roleFunction: 'Pedagógico', career: 'Docente', gender: 'M', email: 'pedagogico@escola.com', phone: '+258 84 100 0002', nuit: '102938476', contractLink: 'Nomeação Definitiva', isEffective: 'Sim', maritalStatus: 'Casado', fatherName: 'Pedagógico Pai', motherName: 'Pedagógica Mãe', idCardNumber: '1102938476B', idCardIssuedAt: 'Maputo', idCardIssuedDate: '2016-08-15', nationality: 'Moçambicana', birthProvince: 'Maputo', birthDistrict: 'KaMpfumo', birthDate: '1978-07-20' },
    { id: 'emp3', schoolId: 's1', name: 'Prof. Alberto Nhatitima', role: 'Professor', roleFunction: 'Professor', career: 'Docente', gender: 'M', email: 'professor@escola.com', phone: '+258 84 100 0003', nuit: '102938477', contractLink: 'Nomeação Definitiva', isEffective: 'Sim', maritalStatus: 'Solteiro', fatherName: 'Nhatitima Pai', motherName: 'Nhatitima Mãe', idCardNumber: '1102938477C', idCardIssuedAt: 'Maputo', idCardIssuedDate: '2018-02-14', nationality: 'Moçambicana', birthProvince: 'Gaza', birthDistrict: 'Xai-Xai', birthDate: '1985-11-04' },
    { id: 'emp4', schoolId: 's1', name: 'Dra. Ana Secretaria', role: 'Chefe da Secretaria', roleFunction: 'Secretaria', career: 'CTA', gender: 'F', email: 'secretaria@escola.com', phone: '+258 84 100 0004', nuit: '102938478', contractLink: 'Nomeação Definitiva', isEffective: 'Sim', maritalStatus: 'Casada', fatherName: 'Secretaria Pai', motherName: 'Secretaria Mãe', idCardNumber: '1102938478D', idCardIssuedAt: 'Maputo', idCardIssuedDate: '2017-06-22', nationality: 'Moçambicana', birthProvince: 'Inhambane', birthDistrict: 'Maxixe', birthDate: '1982-09-18' },
    { id: 'emp5', schoolId: 's1', name: 'Dr. Tomás Tesoureiro', role: 'Gestor Financeiro', roleFunction: 'Financeiro', career: 'CTA', gender: 'M', email: 'financas@escola.com', phone: '+258 84 100 0005', nuit: '102938479', contractLink: 'Contratado', isEffective: 'Não', maritalStatus: 'Casado', fatherName: 'Tesoureiro Pai', motherName: 'Tesoureira Mãe', idCardNumber: '1102938479E', idCardIssuedAt: 'Maputo', idCardIssuedDate: '2020-01-10', nationality: 'Moçambicana', birthProvince: 'Maputo', birthDistrict: 'KaMpfumo', birthDate: '1988-12-01' }
  ],
  collectionPeriods: [],
  collectionForms: [],
  chatMessages: [],
  transferRequests: [],
  academicComplaints: [],
  academicArchives: [],
  emailNotifications: [],
  financialTransactions: [
    {
      id: 'tx1',
      date: '2026-02-10',
      description: 'Propina Fevereiro - Artur Aluno',
      category: 'Propina',
      amount: 1500,
      type: 'income',
      studentName: 'Artur Aluno',
      paymentMethod: 'M-Pesa',
      status: 'pago'
    },
    {
      id: 'tx2',
      date: '2026-02-12',
      description: 'Aquisição de Material de Limpeza e Higiene',
      category: 'Despesa Operacional',
      amount: 4200,
      type: 'expense',
      paymentMethod: 'Transferência Bancária',
      status: 'pago'
    }
  ],
  patrimonyItems: [],
  patrimonyMovements: [],
  libraryBooks: [],
  libraryLoans: [],
  hrContracts: [],
  hrLeaves: [],
  hrPromotions: [],
  hrTrainings: [],
  receptionVisitors: [],
  receptionTickets: [],
  archiveRecords: [],
  classSchedules: [],
  schoolRooms: [],
  aiPredictions: [],
  aiReports: [],
} as any;
