import { INITIAL_PROVINCES, INITIAL_DISTRICTS } from './data/mozambiqueLocations';

export const initialData = {
  users: [
    { id: 'ST849547771', name: 'Administrador Geral', email: 'slaitertripas@gmail.com', role: 'admin' as const, roleTitle: 'Administrador Geral do Sistema', department: 'Tecnologias da Informação', password: '231383', mustChangePassword: false },
    { id: 'u1-gov', name: 'Administrador Geral (Gov)', email: 'admin@gov.mz', role: 'admin' as const, roleTitle: 'Administrador de Sistemas do Governo', department: 'Governo de Moçambique' },
    { id: 'u6', name: 'Ministro da Educação', email: 'ministro@gov.mz', role: 'national' as const, roleTitle: 'Ministro da Educação (MINEDH)', department: 'Gabinete do Ministro' },
    { id: 'u7', name: 'Director Provincial - Maputo', email: 'provincial@gov.mz', role: 'provincial' as const, roleTitle: 'Director Provincial (DPE)', department: 'Direção Provincial de Educação', provinceId: 'p1' },
    { id: 'u8', name: 'Director Distrital - KaMpfumo', email: 'distrital@gov.mz', role: 'district' as const, roleTitle: 'Director Distrital (SDEJT)', department: 'Serviço Distrital de Educação', districtId: 'd1', provinceId: 'p1' },
    { id: 'u2', name: 'Dr. Manuel Mabote', email: 'diretor@escola.com', role: 'director' as const, roleTitle: 'Director Geral da Escola', department: 'Direcção da Escola', schoolId: 's1' },
    { id: 'u3', name: 'Dr. João Pedagógico', email: 'pedagogico@escola.com', role: 'pedagogical' as const, roleTitle: 'Director Adjunto Pedagógico (DAP)', department: 'Pedagógico', schoolId: 's1' },
    { id: 'u4', name: 'Prof. Alberto Nhatitima', email: 'professor@escola.com', role: 'teacher' as const, roleTitle: 'Professor de Matemática', department: 'Corpo Docente', schoolId: 's1' },
    { id: 'u5', name: 'Dra. Ana Secretaria', email: 'secretaria@escola.com', role: 'secretariat' as const, roleTitle: 'Chefe da Secretaria Escolar', department: 'Secretaria Geral', schoolId: 's1' },
    { id: 'u-rh', name: 'Dra. Maria Recursos Humanos', email: 'rh@escola.com', role: 'secretariat_rh' as const, roleTitle: 'Técnica de Recursos Humanos', department: 'Secretaria • RH', schoolId: 's1' },
    { id: 'u-pat', name: 'Sr. Fernando Património', email: 'patrimonio@escola.com', role: 'secretariat_patrimonio' as const, roleTitle: 'Gestor de Património', department: 'Secretaria • Património', schoolId: 's1' },
    { id: 'u-fin', name: 'Dr. Tomás Tesoureiro', email: 'financas@escola.com', role: 'secretariat_financas' as const, roleTitle: 'Tesoureiro / Gestor Financeiro', department: 'Secretaria • Finanças', schoolId: 's1' },
    { id: 'u-rec', name: 'Dra. Sofia Recepção', email: 'recepcao@escola.com', role: 'secretariat_recepcao' as const, roleTitle: 'Atendimento e Recepção', department: 'Secretaria • Atendimento', schoolId: 's1' },
    { id: 'u-arq', name: 'Sr. Paulo Arquivista', email: 'arquivo@escola.com', role: 'secretariat_arquivo' as const, roleTitle: 'Arquivista Escolar', department: 'Secretaria • Arquivo', schoolId: 's1' },
    { id: 'u-bib', name: 'Dra. Beatriz Bibliotecária', email: 'biblioteca@escola.com', role: 'librarian' as const, roleTitle: 'Bibliotecária Principal', department: 'Biblioteca Escolar', schoolId: 's1' },
    { id: 'u-st01', name: 'Artur Aluno', email: 'aluno@escola.com', role: 'student' as const, roleTitle: 'Estudante da 10ª Classe', studentId: 'st01', schoolId: 's1' },
    { id: 'u-enc', name: 'Sr. Carlos Aluno (Encarregado)', email: 'encarregado@escola.com', role: 'guardian' as const, roleTitle: 'Encarregado de Educação', guardianStudentIds: ['st01'], schoolId: 's1' },
  ],
  provinces: INITIAL_PROVINCES,
  districts: INITIAL_DISTRICTS,
  schools: [
    { 
      id: 's1', 
      name: 'Escola Secundária Josina Machel', 
      code: 'ESC-MAP-001',
      managementType: 'estatal',
      province: 'Maputo Cidade', 
      district: 'KaMpfumo', 
      address: 'Av. Mao Tse Tung, nº 1420', 
      districtId: 'd1',
      schoolTypes: ['ENSINO SECUNDÁRIO DO 1 CICLO', 'ENSINO SECUNDÁRIO DO 2 CICLO'],
    }
  ],
  classes: [],
  students: [],
  subjects: [
    { id: 'sub1', name: 'Português', area: 'CS' },
    { id: 'sub2', name: 'Matemática', area: 'MCN' },
    { id: 'sub3', name: 'Inglês', area: 'CS' },
  ],
  assignments: [],
  grades: [],
  examGrades: [],
  reports: [],
  employees: [],
  collectionPeriods: [],
  collectionForms: [],
  chatMessages: [],
  transferRequests: [],
  academicComplaints: [],
  academicArchives: [],
  emailNotifications: [],
  financialTransactions: [],
  patrimonyItems: [],
  patrimonyMovements: [],
  libraryBooks: [],
  libraryLoans: [],
  hrContracts: [],
  hrLeaves: [],
  hrPromotions: [],
  hrTrainings: [],
  receptionVisitors: [],
  receptionTickets: [],
  archiveRecords: [],
  classSchedules: [],
  schoolRooms: [],
  aiPredictions: [],
  aiReports: [],
} as any;
